-
   description: Deputy Chair of Advisory Board, Human Language Technology Center of Excellence (HLTCOE), Johns Hopkins University 2023-2026
-
   description: Advisory Board, Human Language Technology Center of Excellence (HLTCOE), Johns Hopkins University 2016-present
-
   description: Sponsorship Director for the Association for Computational Linguistics, 2020-present
-
   description: Test of Time Award Committee, ACL 2020
-
   description: Best Paper Committee, ACL 2020
-
   description: Director Search Committee, HLTCOE, Johns Hopkins University 2019-2020
-
   description: Secretary-Treasurer for SIGDAT 2016-2018
-
   description: General Chair for ACL 2017
-
   description: Program Co-Chair for EMNLP 2015
-
   description: Past Chair of the NAACL Executive Board 2014-2015
-
   description: Chair of the NAACL Executive Board 2012-2013
-
   description: Board Member for NAACL Executive Board 2010-2011
-
   description: Action Editor for Transactions of the Association for Computational Linguistics 2012-2016
-
   description: Editorial Board for Computational Linguistics 2010-2012
-
   description: Executive Committee, Institute for Research in Cognitive Science (IRCS), University of Pennsylvania 2013-2016
-
   description: Board Member for American Machine Translation Association 2009-2010
-
   description: North American Representative for ACL Special Interest Group in Machine Translation 2009-2010 
-
   description: Senior Area Chair for the Semantics&colon; Sentence-level Semantics, Textual Inference and Other Areas track at ACL-IJCNLP 2021
-
   description: Program Committee Member and/or Area Chair for ACL, NAACL, EMNLP, COLING 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2007-2013
-
   description: Co-Organizer of the Machine Translation Marathon 2007-2010
-
   description: Co-Chair of ACL 2005 Student Research Workshop
-
   description: Chair of Diversity Committee, JHU Computer Science Department
-
   description: Graduate Admissions Committee, JHU Computer Science Department
